version: '3'

services:
  rabbitmq:
    image: rabbitmq:alpine
    ports:
      - "5672:5672"
    volumes:
      - "/home/nathan/development/workspaces/localmovies/amqp-sample/enabled_plugins:/etc/rabbitmq/enabled_plugins"